export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';


export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


//doubt create
export const DOUBT_CREATE_LOADING = 'DOUBT_CREATE_LOADING';
export const DOUBT_CREATE_SUCCESS = 'DOUBT_CREATE_SUCCESS';
export const DOUBT_CREATE_FAILURE = 'DOUBT_CREATE_FAILURE';

//all doubt fetch
export const FETCH_DOUBTS_LOADING = 'FETCH_DOUBTS_LOADING';
export const FETCH_DOUBTS_SUCCESS = 'FETCH_DOUBTS_SUCCESS';
export const FETCH_DOUBTS_FAILURE = 'FETCH_DOUBTS_FAILURE';

//fetch notified list for tutor
export const FETCH_NOTIFIED_LOADING = 'FETCH_NOTIFIED_LOADING';
export const FETCH_NOTIFIED_SUCCESS = 'FETCH_NOTIFIED_SUCCESS';
export const FETCH_NOTIFIED_FAILURE = 'FETCH_NOTIFIED_FAILURE';